### ISSUE TITLE
What is this error ?

### ISSUE THREAD

**Issue by farastyle** [Carbon-Modding/Carbon.Core#39]
Threading compilation failed for 'RustEditAPIExample' (Object reference not set to an instance of an object)
  at Carbon.Jobs.ScriptCompilationThread.ThreadFunction () [0x00295] in <c8ffa07bdd934958a584e93342fc83cd>:0
Failed compiling 'C:\Rustserver\Server\carbon\plugins\RustEditAPIExample.cs':
  1. The type or namespace name 'RustEdit' does not exist in the namespace 'Oxide.Ext' (are you missing an assembly reference?)
I'm having this issue only with Carbon, when I unistall and get back to oxide it disapear

**Comment by farastyle** [comment]
another thing, not sure why it only loads ok when I make the server run from administrator .
if run without it, it crashes

**Comment by jbrazio** [comment]
RustEdit extension is not supported yet.
Concerning the administrator rights it's a bit strange.. can you add more context around the issue ?
