### ISSUE TITLE
Can't pick up deployables

### ISSUE THREAD

**Issue by SShadow1974** [Carbon-Modding/Carbon.Core#47]
Running Carbon v0.23.321.1711
If I load up a completly fresh server without Carbon installed, I do not have this issue.
If I load up Rust with Carbon and no plugins, I have this issue.
Can't seem to figure out what is causing it.
I can't pick up my boxes, workbench, research table or doors with no locks.
No error messages, just won't pick up.
I am set as owner of server. Happens on a freshly wiped server. Happens on default Procedural map as well as custom maps. I am authorized on tool cupboard.
Can't think of anything else to try.

**Comment by SShadow1974** [comment]
It seems Carbon v0.23.322.313 has fixed the problem.

**Comment by jbrazio** [comment]
Closing the issue.
