### ISSUE TITLE
Static Dispensers Plugin doesn't appear to work.

### ISSUE THREAD

**Issue by SShadow1974** [Carbon-Modding/Carbon.Core#48]
Static Dispensers plugin doesn't seem to do anything. No errors that I noticed, but nothing seems to change when plugin loaded.

**Comment by jbrazio** [comment]
Can you please provide a link to the plugin in question ?
Thanks.

**Comment by raulssorban** [comment]
It's my plugin, I'll investigate as I get time :)

**Comment by raulssorban** [comment]
This is fixed. Please do the following: update your server with the latest Carbon version, delete the StaticDispensers empty config file, then boot the server.
