### ISSUE TITLE
Weather Events not working

### ISSUE THREAD

**Issue by SShadow1974** [Carbon-Modding/Carbon.Core#49]
The plugin Weather Events does not work.
[Weather Events](https://umod.org/plugins/weather-events)

**Comment by raulssorban** [comment]
Just tested it myself, it does work, you'll just see the weather change differences very slow (as that's how it's designed).

**Comment by SShadow1974** [comment]
Just checked this morning after updating to Carbon v0.23.323.148 and it is now working.
It wasn't previously as no matter what weather I chose, the weather.report command reported clear|clear|clear.
Thank you to whomever fixed the issue.
