### ISSUE TITLE
Unsuported format/version Carbon.Hooks.Base.dll & Carbon.Hooks.Extra.dll with commit build 9934d72

### ISSUE THREAD

**Issue by PaulFromNZ** [Carbon-Modding/Carbon.Core#50]
Error while loading hooks from 'Carbon.Hooks.Base.dll'.
Either the file is corrupt or has an unsuported format/version.
Error while loading hooks from 'Carbon.Hooks.Extra.dll'.
Either the file is corrupt or has an unsuported format/version.

Also, unsupported is misspelled ^_^;;

**Comment by raulssorban** [comment]
Fixed it :)
