### ISSUE TITLE
Whitelist being enforced, even if whitelist module set disabled.  commit build c04d3ac

### ISSUE THREAD

**Issue by PaulFromNZ** [Carbon-Modding/Carbon.Core#51]
In testing commit build c04d3ac, found that whitelist was being enforced, even if config has it disabled.
192.168.1.2:60769/7XXXXXXXXXXXXXX2/Paul has auth level 2
192.168.1.2:60769/7XXXXXXXXXXXXXX2/Paul Rejecting connection - Not whitelisted
192.168.1.2:60769/7XXXXXXXXXXXXXX2/Paul kicked: Not whitelisted

Whitelist config.json:
{
  "Enabled": false,
  "Config": {
    "BypassPermission": "whitelist.bypass",
    "BypassGroup": "whitelisted"
  }
}

**Comment by raulssorban** [comment]
Currently investigating & testing.

**Comment by raulssorban** [comment]
Fixed it.
