### ISSUE TITLE
XPerience Issue

### ISSUE THREAD

**Issue by SShadow1974** [Carbon-Modding/Carbon.Core#52]
When I try loading the XPerience plugin, it will not load.

> c.load XPerience
Failed compiling 'C:\Rust Server Tool\carbon\plugins\XPerience.cs':
  1. Using the generic type 'ArrayPool<T>' requires 1 type arguments
     (XPerience 41 line 4369)

**Comment by SShadow1974** [comment]
https://umod.org/plugins/xperience

**Comment by raulssorban** [comment]
Fixed here: https://github.com/CarbonCommunity/Carbon.Core/commit/f4bfd63ee6526026565e92484b5fb8ebcdeff611
