### ISSUE TITLE
[REQ] Add support for subdirectories

### ISSUE THREAD

**Issue by Xenius97** [Carbon-Modding/Carbon.Core#59]
If possible, please add subdirectory support for plugins.

Example layout:
- [ ] plugins/core/mysql.cs
- [ ] plugins/core/permissions.cs
- [ ] plugins/fixes/FixCargoshipRHIB.cs
- [ ] etc ...

Currently you will get an error message if you try this.

**Comment by raulssorban** [comment]
Added :)

**Comment by Xenius97** [comment]
That was fast. Coooool :)

**Comment by Xenius97** [comment]
Sometimes you will get an error like this:
```
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
Attempted to compile an empty string of source code.
```

![image](https://github.com/CarbonCommunity/Carbon.Core/assets/6568348/32f81468-c882-47af-9e02-dffba4a49301)


@raulssorban
