### ISSUE TITLE
"-carbon.rootdir" switch doesn`t working 

### ISSUE THREAD

**Issue by Xilo14** [Carbon-Modding/Carbon.Core#62]
I renamed the carbon folder to carbon2. Now my startup script looks like this:
```
RustDedicated.exe -nographics -batchmode -logs -silent-crashes ^
                  -server.hostname "%name%" ^
                  -server.identity "%identity%" ^
                  -server.port %port% ^
                  -server.queryport %queryport% ^
                  -server.netlog ^
                  -server.saveinterval 400 ^
                  -rcon.port %rconPort% ^
                  -rcon.password "%rconPassword%" ^
                  -rcon.web true ^
                  -server.maxplayers 50 ^
                  -chat.serverlog 1 ^
                  -logfile "%identity%_log.txt" ^
                  -carbon.rootdir "D://path//to//carbon2//"
```

But when I try to start the server, all I have is an empty console output.
Without any errors. All logs are also empty.
I need this to run multiple server instances locally.

**Comment by raulssorban** [comment]
Try -carbon.rootdir "D:/path/to/carbon2" ^

**Comment by raulssorban** [comment]
Lemme know if that fixed it :)

**Comment by Xilo14** [comment]
> Try -carbon.rootdir "D:/path/to/carbon2" ^

It didn't help.

> Lemme know if that fixed it :)

To fix the problem, you need to edit doorstop_config.ini:
`target_assembly = carbon2/managed/Carbon.Preloader.dll`
