### ISSUE TITLE
Mods that interact / change other mods seem to have protection issues and refuse to load

### ISSUE THREAD

**Issue by LaernuTairos** [Carbon-Modding/Carbon.Core#69]
Example:

Zombie Horde loads fine

Raiding zombies alters the behavior of Zombie Horde, and refuses to load in Carbon, this works properly in Oxide however.

(Ran into a lot of issues where other mods have similar problems if they interact the same way)

[ERRO] Failed compiling '\carbon\plugins\RaidingZombies.cs':
[ERRO]   1. 'ZombieHorde' is inaccessible due to its protection level [CS0122]
     (RaidingZombies 30 line 142)

Link to above example mods
https://chaoscode.io/resources/raiding-zombies.211/
https://chaoscode.io/resources/zombiehorde.120/

**Comment by raulssorban** [comment]
This is due to developers setting the primary plugin type visibility to private, hence other plugins being unable to access them; this is the developers' fault.

This works on oxide because they do not respect any of this logic that should be in place in the first place.

**Comment by raulssorban** [comment]
An easy fix is to just renaming the plugin type from "private" or "internal", or if there's none, ensuring it's this: "public class ZombieHorde : ChaosPlugin"

**Comment by LaernuTairos** [comment]
Thanks Raul, will try this and report back in a few hours.

(Incase someone in the future looks up the issue)

Edit:
Alright so I made the class public, got a bunch of Inconsistent accessibility errors, changed the errors on the line #'s shown from public to internal on 2 lines, and Raiding Zombies loaded up finally. TYVM!
