### ISSUE TITLE
Windows Artifacts Are non-Standards Compliant .zip files.

### ISSUE THREAD

**Issue by Sewer56** [Carbon-Modding/Carbon.Core#70]
The build script (`build.bat`) uses PowerShell to compress files on a Windows Runner, which in turn runs on old .NET Framework and produces non-standard compliant files:

https://github.com/CarbonCommunity/Carbon/blob/7524f6fa332ae9fda1c708afcbcc2d233dc8cb1f/Tools/Build/win/build.bat#L79

(The separators in the `.zip` archive are `\\` backslashes instead of forward slashes `/`), more info here:
https://github.com/microsoft/dotnet/blob/main/Documentation/compatibility/change-in-path-separator-character-in-zip-files.md

A quick fix would just be invoking PowerShell Core (`pwsh`), that should be preinstalled on CI machines.

----------

Note: I don't know anything about Rust (game), I was just linked the repo and poked around.

Generally the impact of this is some unarchiving tools (more so on Linux side), may be unhappy with these archive files.

**Comment by raulssorban** [comment]
Thanks for that! Really appreciate it. I'll check it out.

**Comment by HunterZ** [comment]
Ironically I just figured out all of this independently today and posted a suggestion in Discord. I think Raul just fixed it via 1dddebbb7ab1917947c3b91d739986176e78153d

**Comment by Sewer56** [comment]
That was my initial suggestion, yeah. Should be fixed now.
I'll leave it to repo owners to close, looks good to me.

**Comment by raulssorban** [comment]
Thank you both. All good! Gets merged across all branches on 7th.
