### ISSUE TITLE
c.ovenspeedmultiplier doesnt work

### ISSUE THREAD

**Issue by WeirdPhrog** [Carbon-Modding/Carbon.Core#71]
c.ovenspeedmultiplier does nothing

**Comment by raulssorban** [comment]
It's a multiplier. The lower the value, the faster the oven processes. Make sure that your ovens aren't under the `c.ovenblacklist` array of prefabs that are ignored.

**Comment by WeirdPhrog** [comment]
> It's a multiplier. The lower the value, the faster the oven processes. Make sure that your ovens aren't under the `c.ovenblacklist` array of prefabs that are ignored.

Thanks
