### ISSUE TITLE
OnIORefCleared Oxide hook does not match signature of Oxide, causing PowerlessElectronics mod to fail compiling

### ISSUE THREAD

**Issue by silbinarywolf** [Carbon-Modding/Carbon.Core#75]
**Carbon Version:**  v2.0.142.0
**Link to mod using this hooks Github:** https://github.com/WheteThunger/PowerlessElectronics/blob/master

The issue seems to stem from Carbon missing the `IOEntity ioEntity` parameter from it's compatibility layer.

**Carbon Function signature**
```c#
void OnIORefCleared(IOEntity.IORef IORef)
{
    Puts("OnIORefCleared was called!");
}
```
Source: https://docs.carbonmod.gg/docs/core/hooks/electronic#oniorefcleared
Web Archive: https://web.archive.org/web/20241003065314/https://docs.carbonmod.gg/docs/core/hooks/electronic#oniorefcleared

**Oxide Function signature**
```c#
void OnIORefCleared(IOEntity.IORef ioRef, IOEntity ioEntity)
{
    ProcessIOEntity(ioEntity, delay: true);
}
```
Source: https://umod.org/documentation/games/rust#oniorefcleared
Web Archive: http://web.archive.org/web/20241003065151/https://umod.org/documentation/games/rust?__cf_chl_rt_tk=uTR8dc74aXIV8YvBsjMUwIVB7dpLhTrcmfiAoPoQPoE-1727938311-0.0.1.1-4479#oniorefcleared

That's causing the following:
```
(16:11:42) | A hook request for 'OnIORefCleared[4b05aa]' received:
(16:11:42) | - The current status is FAILURE: Invalid IL code in (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:IOEntity+IORef.Clear_Patch0 (IOEntity/IORef): IL_0022: ret
(16:11:42) | - Check for possible errors on the log file
(16:11:42) | Error while patching hook 'OnIORefCleared[4b05aa]' (Invalid IL code in (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:IOEntity+IORef.Clear_Patch0 (IOEntity/IORef): IL_0022: ret
```

**Comment by raulssorban** [comment]
Hey there! Thank you for reporting. Currently investigating.

**Comment by raulssorban** [comment]
I identified the cause. Currently patching the error.

**Comment by raulssorban** [comment]
Fixed! Currently rebuilding production hooks with the fix.
https://github.com/CarbonCommunity/Carbon/actions/runs/11280262739
